# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  rid: 'linux-x64'

stages:
- stage: build
  displayName: 'Build and Test Stage'

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
        packageType: sdk

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: build
        arguments: '-r $(rid) --configuration $(buildConfiguration) /p:SourceRevisionId=$(Build.SourceVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        command: 'test'
        projects: '**/*tests/*.csproj'
        arguments: '--runtime $(rid) --configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-r $(rid) --no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'webapp'
        publishLocation: 'pipeline'

- stage: Deploy
  jobs:
  - job: Deploy
    displayName: 'Deploy to Dev'
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
       artifactName: 'webapp'
       itemPattern: '**/*.zip'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureserviceconnection)
        appType: 'webAppLinux'
        appName: $(webappname)
        package: '$(Pipeline.Workspace)/**/*.zip'
       
      
      
